# Generated by Django 3.0.4 on 2020-06-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone Number')),
                ('previous_response', models.CharField(max_length=160, verbose_name='Last Response')),
            ],
        ),
    ]
