# Generated by Django 3.0.4 on 2020-06-20 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['phone']},
        ),
    ]
