# Generated by Django 3.0.4 on 2020-06-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_auto_20200620_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='enemyTraveled',
            field=models.IntegerField(default=-20, verbose_name='Enemy Traveled'),
        ),
    ]
