# Generated by Django 3.0.4 on 2020-06-21 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_auto_20200621_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='camelTirednes',
            new_name='camelTiredness',
        ),
    ]
